@echo off
TITLE ACEA SENTINEL - PROJECT SETUP
COLOR 0B

echo.
echo  ===========================================================
echo       _    ____ _____    _      ____  _____ _   _ _____
echo      / \  / ___^| ____|  / \    / ___^|^| ____^| \ ^| ^|_   _^|
echo     / _ \^| ^|   ^|  _^|   / _ \   \___ \^|  _^| ^|  \^| ^| ^| ^|
echo    / ___ \ ^|___^| ^|___ / ___ \   ___) ^| ^|___^| ^|\  ^| ^| ^|
echo   /_/   \_\____^|_____/_/   \_\ ^|____/^|_____^|_^| \_^| ^|_^|
echo.
echo              FIRST - TIME   PROJECT   SETUP
echo  ===========================================================
echo.

:: ─────────────────────────────────────────────────────────
:: 1. Check Prerequisites
:: ─────────────────────────────────────────────────────────
echo  [1/6] Checking prerequisites...

where python >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] Python is not installed or not in PATH.
    echo  Please install Python 3.12+ from https://www.python.org/downloads/
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo         Found: %PYTHON_VERSION%

where node >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] Node.js is not installed or not in PATH.
    echo  Please install Node.js 18+ from https://nodejs.org/
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('node --version 2^>^&1') do set NODE_VERSION=%%i
echo         Found: Node %NODE_VERSION%

where npm >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] npm is not installed or not in PATH.
    pause
    exit /b 1
)

for /f "tokens=*" %%i in ('npm --version 2^>^&1') do set NPM_VERSION=%%i
echo         Found: npm v%NPM_VERSION%
echo         OK!
echo.

:: ─────────────────────────────────────────────────────────
:: 2. Create Python Virtual Environment
:: ─────────────────────────────────────────────────────────
echo  [2/6] Setting up Python virtual environment...

if exist "backend\venv\Scripts\activate.bat" (
    echo         venv already exists — skipping creation.
) else (
    echo         Creating venv at backend\venv ...
    python -m venv backend\venv
    if %ERRORLEVEL% NEQ 0 (
        echo  [ERROR] Failed to create virtual environment.
        pause
        exit /b 1
    )
    echo         Created!
)
echo.

:: ─────────────────────────────────────────────────────────
:: 3. Install Python Dependencies
:: ─────────────────────────────────────────────────────────
echo  [3/6] Installing Python dependencies...
echo         This may take a few minutes on first run...

call backend\venv\Scripts\activate.bat

pip install --upgrade pip >nul 2>&1
pip install -r backend\requirements.txt
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] Failed to install Python dependencies.
    echo  Check backend\requirements.txt for issues.
    pause
    exit /b 1
)
echo         Python dependencies installed!
echo.

:: ─────────────────────────────────────────────────────────
:: 4. Install Playwright Browsers
:: ─────────────────────────────────────────────────────────
echo  [4/6] Installing Playwright browsers...
echo         (needed for browser-based testing features)

python -m playwright install chromium >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [WARN] Playwright browser install failed. Browser features may not work.
    echo         You can retry later with: python -m playwright install chromium
) else (
    echo         Chromium installed!
)
echo.

:: ─────────────────────────────────────────────────────────
:: 5. Install Frontend Dependencies
:: ─────────────────────────────────────────────────────────
echo  [5/6] Installing frontend dependencies (npm)...
echo         This may take a minute...

cd frontend
call npm install
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] npm install failed.
    cd ..
    pause
    exit /b 1
)
cd ..
echo         Frontend dependencies installed!
echo.

:: ─────────────────────────────────────────────────────────
:: 6. Create .env file from template
:: ─────────────────────────────────────────────────────────
echo  [6/6] Setting up environment config...

if exist "backend\.env" (
    echo         backend\.env already exists — skipping.
    echo         (delete it and re-run setup to regenerate^)
) else (
    (
        echo # ========== ACEA Backend — Environment Variables ==========
        echo # Generated by setup_acea.bat
        echo #
        echo # LOCAL DEV: Only GEMINI_API_KEYS is required. Everything else has safe defaults.
        echo # PRODUCTION ^(Railway^): Set all variables marked [REQUIRED].
        echo.
        echo # ---- Environment ----
        echo ENVIRONMENT=development
        echo.
        echo # ---- API Keys [REQUIRED] ----
        echo # Add your Gemini API keys, comma-separated for rotation
        echo GEMINI_API_KEYS=your_key_1,your_key_2
        echo # Get from https://e2b.dev/
        echo E2B_API_KEY=your_e2b_key
        echo.
        echo # ---- Database ----
        echo # Local: uses SQLite ^(default, no setup needed^)
        echo # Production: set to your PostgreSQL URL
        echo DATABASE_URL=sqlite:///./acea.db
        echo.
        echo # ---- Redis ----
        echo # Local: optional ^(falls back to in-memory^)
        echo REDIS_URL=redis://localhost:6379
        echo USE_REDIS_PERSISTENCE=false
        echo.
        echo # ---- Frontend URL ^(CORS^) ----
        echo FRONTEND_URL=
        echo.
        echo # ---- Security ----
        echo JWT_SECRET=supersecretkey_change_me_in_production
        echo.
        echo # ---- Optional ----
        echo CODESANDBOX_API_KEY=
        echo DAYTONA_API_KEY=
    ) > backend\.env

    echo         Created backend\.env with template values.
    echo         [ACTION REQUIRED] Edit backend\.env and add your API keys:
    echo           - GEMINI_API_KEYS  (from https://aistudio.google.com/apikey^)
    echo           - E2B_API_KEY      (from https://e2b.dev/^)
)
echo.

:: ─────────────────────────────────────────────────────────
:: Done!
:: ─────────────────────────────────────────────────────────
echo.
echo  ===========================================================
echo       SETUP COMPLETE!
echo  ===========================================================
echo.
echo  Next steps:
echo    1. Edit backend\.env and add your API keys
echo    2. Run start_acea.bat to launch the project
echo.
echo  ===========================================================
echo.
pause
